name: buildandtest

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - run: |
          cd Lab1/
          make main_test
          ./main_test
