name: Builder

on:
  push:
    branches: [ main ]

jobs:
  build:


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
            cd Lab1-2
            make main_2test
    - run: |
           cd Lab1-2 
           ./main_test
